FORMAT: 1A
HOST: https://video-ads-module.media.nbcuni.com/v1/

# Video Ads Module v1 (for D2C)

The **Video Ads Module (VAM)** service is used by the client application to retrieve the 
[Freewheel URL](https://hub.freewheel.tv/pages/viewpage.action?spaceKey=techdocs&title=HTTP+GET+Ad+Request+and+SmartXML+Response) 
it should call in order to request the video multiple ad playlist 
([VMAP](https://www.iab.com/guidelines/digital-video-multiple-ad-playlist-vmap-1-0-1/)) 
document for a particular video stream.

## See Also

[NBCU Ad Sales Solutions: Video Ads User Stories](https://wiki.inbcu.com/display/SSH/7%29+User+Stories)

# Freewheel URL [/freewheel-url?{brand,platform,streamType,videoSpec,videoAssetId,videoDurationInSeconds,httpUserAgent,httpReferer,mvpdCanonicalName,locationLatitude,locationLongitude,locationCountry,locationState,locationCity,locationDma,locationPostalCode,gdprApplies,gdprTrackingConsentString,coppaApplies,playerWidthPixels,playerHeightPixels,deviceType,deviceId,subscriberIdObfuscated,appName,appBuildNumber,sdkName,playerName,cdnName,deviceTrackingConsent,gdprTargetingConsent,mpsWebSectionPath}]

+ Parameters

    + brand (enum[string], required)
            
        NBCU brand identifier.
        
    + platform (enum[string], required)
    
        String describing the hardware/software platform that the client app is running on.
        
    + streamType (enum[string], required)
    
        String describing the temporal nature of the stream. _linear_ refers to the national broadcast video
        stream that is being transmitted to MVPDs. _live_ refers to a live event that isn't being transmitted to MVPDs,
        such as all of the parallel live feeds that we generate during the Olympics. 
        
        + `vod`
        + `linear`
        + `live`

    + videoSpec (string, required)
    
        String created by the client app that represents the combination of:
        - Adaptive bit rate (ABR) type
        - Frame rate

    + videoAssetId (string, required)
    
        Unique ID for the video asset that the user is watching.
    
    + videoDurationInSeconds (number, required)
    
        Must be a positive integer.
    
    + httpUserAgent (string, required)
    
        Used to understand which devices/platforms we're serving ads to.
        
    + httpReferer (string, optional)
    
        Sent by web browsers only.
        
    + mvpdCanonicalName (string, required)
    
        Canonical MVPD name string. VAM will use the canonical MVPD name string to find a corresponding hash value
        in [this file](https://tve-common.nbcuni.com/web/js/nbcuni_hash_config.js).
        (The hash value is what will get passed to Freewheel.)
        
        If a user is a D2C-only customer, then pass "D2C" as the MVPD name.
        
    + locationLatitude (number, optional)
    
    + locationLongitude (number, optional)
    
    + locationCountry (string, optional)
    
    + locationState (string, optional)
    
    + locationCity (string, optional)
    
    + locationDma (string, optional)
    
    + locationPostalCode (string, optional)
    
    + gdprApplies (boolean, required)
    
    + gdprTrackingConsentString (string, required)
    
    + coppaApplies (boolean, required)
    
    + playerWidthPixels (number, required)
    
    + playerHeightPixels (number, required)
    
    + deviceType (string, required)
    
    + deviceId (string, required)
    
        This value will be ignored for COPPA users.
    
    + subscriberIdObfuscated (string, required)
    
    + appName (string, required)
    
    + appBuildNumber (string, required)
    
    + sdkName (string, required)
    
    + playerName (string, required)
    
    + cdnName (string, required)
    
    + deviceTrackingConsent (boolean, required)
    
    + gdprTargetingConsent (boolean, required)
    
    + mpsWebSectionPath (string, optional)
    
    

# Get Freewheel URL [GET /freewheel-url?{brand,platform,streamType,videoSpec,videoAssetId,videoDurationInSeconds,httpUserAgent,httpReferer,mvpdCanonicalName,locationLatitude,locationLongitude,locationCountry,locationState,locationCity,locationDma,locationPostalCode,gdprApplies,gdprTrackingConsentString,coppaApplies,playerWidthPixels,playerHeightPixels,deviceType,deviceId,subscriberIdObfuscated,appName,appBuildNumber,sdkName,playerName,cdnName,deviceTrackingConsent,gdprTargetingConsent,mpsWebSectionPath}]

The client calls this and gets the Freewheel URL from **freewheelUrl** in the response. 

All of the parameters that are passed in are used to determine the exact set of Freewheel parameters to include in
the Freewheel URL.

+ Response 200 (application/json)

    + Body
    
            {
                "freewheelUrl": "https://[customerId].v.fwmrm.net/ad/g/1?[globalParams];[keyValues];[ParamsForSlot1];[ParamsForSlot2];...;[ParamsForSlotN];"
            }

# Get Freewheel URL (debug version) [GET /freewheel-url?{debug,brand,platform,streamType,videoSpec,videoAssetId,videoDurationInSeconds,httpUserAgent,httpReferer,mvpdCanonicalName,locationLatitude,locationLongitude,locationCountry,locationState,locationCity,locationDma,locationPostalCode,gdprApplies,gdprTrackingConsentString,coppaApplies,playerWidthPixels,playerHeightPixels,deviceType,deviceId,subscriberIdObfuscated,appName,appBuildNumber,sdkName,playerName,cdnName,deviceTrackingConsent,gdprTargetingConsent,mpsWebSectionPath}]

The debug version returns the same **frewheelUrl** value, plus the exploded set of Freewheel parameters embedded in the URL.

+ Parameters

    + debug (enum[number], optional)
            
        Optional "debug" mode so that the response contains an exploded JSON version of all the parameters
        in the Freewheel URL. This is easier to read when you're debugging.
        
        If you pass **debug=1** or **debug=**_string_ or simply pass **debug** by itself, you will get the debug
        response.
        
        If the **debug** parameter is missing, or if you pass **debug=0**, you will get the normal response
        without any debug info.
        
        + Default: `0`
        
        + Members
            + `0`
            + `1`
            
+ Response 200 (application/json)

    + Body
    
            {
                "freewheelUrl": "https://[customerId].v.fwmrm.net/ad/g/1?[globalParams];[keyValues];[ParamsForSlot1];[ParamsForSlot2];...;[ParamsForSlotN];"
                "freewheelParameters":
                {
                    "globalParameters": 
                    {
                        "key": "value",
                        ...
                    },
                    "freewheelKeyValues":
                    {
                        "key": "value",
                        ...
                    },
                    "nbcuKeyValues":
                    {
                        "key": "value",
                        ...
                    },
                    "slotParameters":
                    {
                        "key": "value",
                        ...
                    }
                }
            }